import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Level } from "./_components/level";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Level>{children}</Level>
      </body>
    </html>
  );
}
